### ISSUE TITLE
Issue 001 - ValueError: seek of closed file at File.title_exists()

### ISSUE THREAD

**Issue by ColtBaldridge** [ColtBaldridge/pdf-renamer#4]
### Source Error
```
Traceback (most recent call last):
  File "script.py", line 122, in <module>
    main()
  File "script.py", line 110, in main
    if not active_file.title_exists():
  File "script.py", line 73, in title_exists
    if '/Title' not in self.metadata or self.metadata['/Title'] == '':
  File "C:\Users\coltb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyPDF2\generic.py", line 516, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "C:\Users\coltb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyPDF2\generic.py", line 178, in getObject
    return self.pdf.getObject(self).getObject()
  File "C:\Users\coltb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyPDF2\pdf.py", line 1598, in getObject
    self.stream.seek(start, 0)
ValueError: seek of closed file
```

**Comment by ColtBaldridge** [comment]
Issue fixed with commit 8072847a63a8f0267c85c99dfbee35df4f7d89f3
